services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: home-assistant
    restart: unless-stopped
    privileged: false
    network_mode: host
    environment:
      TZ: TZ=America/Montreal
    volumes:
      - "/volume1/docker/home-assistant:/config"
      - /etc/localtime:/etc/localtime:ro
    mem_limit: 2g
    cpus: 2.0
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
  
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - "1883:1883"
    command: "mosquitto -c /mosquitto-no-auth.conf"
    volumes:
      - /volume1/docker/mosquitto:/mosquitto/data

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: ghcr.io/koenkk/zigbee2mqtt
    restart: unless-stopped
    depends_on:
      - mosquitto
    volumes:
        - /volume1/docker/zigbee2mqtt/data:/app/data
        - /run/udev:/run/udev:ro
    ports:
        # Frontend port
        - 8090:8080
    environment:
        - TZ=America/Montreal
    devices:
        - /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0:/dev/ttyUSB0