services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: always
    devices:
      - /dev/dri:/dev/dri  # Integrated graphics
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Montreal
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /volume2/volume2:/MediaVol2 #Library location
    ports:
      - 9096:8096/TCP
    networks:
      - arr_stack
      
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=0
      - TZ=America/Montreal
    volumes:
      - /volume1/docker/radarr/config:/config
      - /volume2/volume2:/media
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - arr_stack

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=0
      - TZ=America/Montreal
    volumes:
      - /volume1/docker/sonarr/config:/config
      - /volume2/volume2:/media
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - arr_stack

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Montreal
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /volume1/docker/jackett/data:/config
      - /volume1/torrent-blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - arr_stack

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - PUID=1000
      - PGID=0
      - TZ=America/Montreal
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
    networks:
      - arr_stack

  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: seerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Montreal
      - PORT=5055
    ports:
      - 5055:5055
    volumes:
      - /volume1/docker/seerr/config:/app/config
    restart: unless-stopped
    networks:
      - arr_stack

  qbittorrent:
    image: ghcr.io/hotio/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Montreal
      - WEBUI_PORTS=8081/tcp,8081/udp
      - LIBTORRENT=v1
      - VPN_ENABLED=true 
      - VPN_CONF=wg0 
      - VPN_PROVIDER=generic 
      - VPN_LAN_NETWORK=192.168.2.0/24
      - VPN_LAN_LEAK_ENABLED=false 
      - VPN_AUTO_PORT_FORWARD=false 
      - VPN_HEALTHCHECK_ENABLED=true 
      - VPN_NAMESERVERS=1.1.1.1,8.8.8.8
      - PRIVOXY_ENABLED=false 
      - UNBOUND_ENABLED=false 
    cap_add:
      - NET_ADMIN
    volumes:
      - /volume1/docker/qbittorrent/config:/config
      - /volume2/volume2:/media
    ports:
      - 8081:8081
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - arr_stack

networks:
  arr_stack:
    driver: bridge